### ISSUE TITLE
Only finds one 2.0 Base station + errors

### ISSUE THREAD

**Issue by Immersive-Matthew** [nouser2013/lighthouse-v2-manager#5]
Hello,

I have 2 Valve 2.0 Base Stations and it looks like only one can been found with this utility plus I get errors and no shortcut created.  I can see both light houses in SteamVR and both track just fine.  Love to get this working as mine just do not turn off/on reliably.  This is what I am getting in the command console.:

C:\Program Files\LH-Manager>lighthouse-v2-manager.exe discover --create-shortcuts

=== LightHouse V2 Manager ===

>> MODE: discover suitable V2 lighthouses
         and create desktop shortcuts

>> Discovering BLE devices...
>> Found potential Valve Lighthouse at 'D6:54:14:C1:CC:1B' with name 'LHB-500EBEA4'...
Traceback (most recent call last):
  File "lighthouse-v2-manager.py", line 155, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "lighthouse-v2-manager.py", line 58, in run
  File "site-packages\bleak-0.6.1-py3.8.egg\bleak\backends\client.py", line 44, in __aenter__
  File "site-packages\bleak-0.6.1-py3.8.egg\bleak\backends\dotnet\client.py", line 145, in connect
  File "site-packages\bleak-0.6.1-py3.8.egg\bleak\backends\dotnet\client.py", line 236, in get_services
bleak.exc.BleakDotNetTaskError: Could not get GATT services.
[61636] Failed to execute script lighthouse-v2-manager

Thanks for taking the time to look at this.  

Cheers,
Immersive Matthew

**Comment by nouser2013** [comment]
Greetings, thanks for reporting this. Since it seems to be working with many other installations, I'm assuming it's something in your particular case.

Searching for the error message in `bleak` yields a [bleak issue](https://github.com/hbldh/bleak/issues/63) where the OP stated that the device he wants to connect to only accepts one single BLE connection. I would conclude this is the same for Valve Lighthouses. 

Could you kill all steam apps, processes and services and try again? Presumably this resolves the issue and I'd release a fix with more `try:`'s in it 😄

**Comment by nouser2013** [comment]
No reply from OP, closing. If shutting down Steam VR apps and services did not help, please reopen.
